
# CyberRename Configuration

# Settings for item names
names:
  # Sets the max length of custom item names, including formatting codes
  max_length: 64
  # Name cost settings
  # If xp is enabled, players will be charged the set number of levels every
  # time they change or reset the custom name of an item
  cost:
    xp:
      enabled: true
      levels: 3

# Settings for item lores
lores:
  # Sets the max length of lores, including formatting codes
  max_length: 512
  # Lore cost settings
  # If xp is enabled, players will be charged the set number of levels every
  # time they change or remove the lore of an item
  cost:
    xp:
      enabled: true
      levels: 3
  # Players can use this character in their lores to move to the next line
  newline_string: "|"

# Preview GUI settings
# When enabled, players will be shown a preview of their item before changing
# its name or lore, and be given "Confirm" and "Cancel" buttons
preview_gui:
  enabled: true
  # GUI text elements
  text:
    title: "&3Preview item"
    button_cancel: "&cCancel"
    button_confirm: "&aConfirm"

# Messages
messages:
  reloaded: "&aConfig reloaded!"
  name_changed: "&aYour item has been renamed to &r%0&r&a!"
  name_removed: "&aYour item's name has been reset!"
  name_too_long: "&cYour item name must be under %0 characters!"
  lore_changed: "&aYour item's lore has been changed!"
  lore_removed: "&aYour item's lore has been removed!"
  lore_too_long: "&cYour lore must be under %0 characters!"
  charge_xp: "&aYou were charged %0 experience levels!"
  not_enough_xp: "&cYou don't have the required %0 experience levels!"
  disallowed_formatting: "&6You don't have permission to use &e%0&6!"
  holding_air: "&cPut an item in your main hand, then try again!"
  item_mismatch: "&cYou aren't holding the same item!"
  player_only: "&cOnly players can run this command!"

# Changing this value will wipe your config!
config_version: 1