main: org.simplecyber.rename.Plugin
name: CyberRename
api-version: 1.19
version: 1.0.0
description: Allow players to change the name and lore of their items with commands!
commands:
  setname:
    aliases: [rename]
    usage: /rename [name]
    description: Sets or removes the custom name on the item in your hand.
    permission: cyberrename.name
  setlore:
    aliases: [lore]
    usage: /relore [lore]
    description: Sets or removes the lore on the item in your hand.
    permission: cyberrename.lore
  crename:
    usage: /crename [reload]
    description: Manage CyberRename.
    permission: cyberrename.info
permissions:
  cyberrename.info:
    default: true
  cyberrename.name:
    default: op
  cyberrename.name.bypassLengthLimit:
    default: op
  cyberrename.name.bypassCost:
    default: op
  cyberrename.lore:
    default: op
  cyberrename.lore.bypassLengthLimit:
    default: op
  cyberrename.lore.bypassCost:
    default: op
  cyberrename.admin:
    default: op