main: org.simplecyber.tpr.Plugin
name: CyberTPR
api-version: 1.19
version: 1.2.2
description: Let users teleport to random locations within a set radius of spawn.
commands:
  rename: [rname, setname]
    usage: /rename <set|remove> [name]
    description: Renames or removes the custom name on the item in your hand.
    permission: cyberrename.rename
  relore:
    aliases: [lore, setlore]
    usage: /relore <set|remove> [lore]
    description: Sets or removes the lore on the item in your hand.
    permission: cyberrename.lore
  cybertpr:
    usage: /cyberrename [reload]
    description: Manage CyberRename.
    permission: cyberrename.info
permissions:
  cyberrename.info:
    default: true
  cyberrename.rename:
    default: op
  cyberrename.lore:
    default: op
  cyberrename.admin:
    default: op